name: Playwright Tests on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
  SPOTIFY_BASE_URL: ${{ vars.SPOTIFY_BASE_URL}}
  SPOTIFY_ACCOUNTS_URL: ${{ vars.SPOTIFY_ACCOUNTS_URL }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Setup node.js env
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Firefox Browser
        run: npx playwright install --with-deps firefox
      - name: Run Playwright API tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
